plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.170'
}

boolean ponderInWorkspace = rootProject.hasProperty('multiModWorkspace.ponder')

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories {
    maven { url = "https://maven.createmod.net" } // Ponder, Flywheel
    maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven" }
    maven { url = "https://mvn.devos.one/snapshots" } // Registrate
    maven { url = "https://www.cursemaven.com" }
    mavenLocal()
    mavenCentral()
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

runs {
    configureEach {
        systemProperty 'neoforge.logging.markers', 'REGISTRIES'
        systemProperty 'neoforge.logging.console.level', 'debug'

        modSource project.sourceSets.main
    }

    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        argument '--nogui'
    }

    gameTestServer {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    data {
        arguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

minecraft{
    accessTransformers{
        file(ATFile)
    }
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"

    jarJar(implementation("com.tterrag.registrate:Registrate:${registrate_version}"))
    jarJar("net.createmod.ponder:Ponder-NeoForge-${minecraft_version}:${ponder_version}")
    if (ponderInWorkspace) {
        implementation(project(":ponder:Common"))
        implementation(project(":ponder:NeoForge"))
    } else {
        implementation("net.createmod.ponder:Ponder-NeoForge-${minecraft_version}:${ponder_version}")
    }

    implementation "curse.maven:create-328085:7178775"
    implementation "curse.maven:storage-drawers-223852:5979167"
    implementation "curse.maven:supermartijn642s-core-lib-454372:6076757"
    implementation "curse.maven:supermartijn642s-config-lib-438332:5546996"
    implementation "curse.maven:trash-cans-394535:5550159"
    implementation "curse.maven:titanium-287342:6337206"
    implementation "curse.maven:functional-storage-556861:6189752"
    implementation "curse.maven:applied-energistics-2-223794:6399563"
    implementation "curse.maven:guideme-1173950:6488254"
    implementation "curse.maven:sophisticated-core-618298:6470497"
    implementation "curse.maven:sophisticated-backpacks-422301:6479794"
    implementation "curse.maven:refined-storage-243076:6391989"
    implementation "curse.maven:codechicken-lib-1-8-242818:6583751"
    implementation "curse.maven:ender-storage-1-8-245174:6159037"
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

def GameTestConfig = project.properties.get('GameTestConfig','default')

tasks.register("prepareGameTestConfigs", Copy) {
    group = 'mod development'
    description = "Copy config files for GameTestServer"
    if(GameTestConfig != 'default') {
        def configFiles = project.file(GameTestConfigDir)
        if (!configFiles.exists() || !configFiles.isDirectory()) {
            throw new GradleException("config set directory '${configFiles}' does not exist for GameTestServer. ")
        }
        from fileTree("${configFiles}/${GameTestConfig}")
        into new File('runs/gameTestServer/config')
    }
}

tasks.configureEach { task ->
    if(task.name == 'runGameTestServer') {
        task.dependsOn(tasks.named('prepareGameTestConfigs').get())
    }
}
