name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - src/*
      - gradle/*
      - .github/workflows/*
      - build.gradle
      - gradle.properties
      - settings.gradle

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.4'

      - name: Build with Gradle
        run: gradle build

      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-tag: 1.19.2-Forge
          github-draft: true
          github-prerelease: false

      - uses: actions/upload-artifact@v4
        with:
          overwrite: true
          include-hidden-files: true
          path: |
            **/logs/
            **/crash-reports/
            build/libs
          retention-days: 1
        if: always()

  GameTest:
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        GameTestConfig: [ default, testAE ]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.4'

      - name: Test Server with ${{ matrix.GameTestConfig }}
        run: gradle runGameTestServer -PGameTestConfig=${{ matrix.GameTestConfig }}
        continue-on-error: true

      - uses: actions/upload-artifact@v4
        with:
          name: Test Artifact of ${{ matrix.GameTestConfig }}
          include-hidden-files: true
          path: |
            **/logs/
            **/crash-reports/
            build/libs
          retention-days: 7
        if: always()