name: Test PR
on:
  workflow_dispatch:
  pull_request:
jobs:
  toLowerCase:
    runs-on: ubuntu-latest
    outputs:
      lower_repository: ${{ steps.toLowerCase.outputs.lower_repository }}
    steps:
      - name: Lowercase the repo name
        id: toLowerCase
        run: echo "lower_repository=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT
  GameTest:
    needs: toLowerCase
    strategy:
      matrix:
        GameTestConfig: [ default, testAE ]
    permissions:
      contents: write
      packages: read
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/${{ needs.toLowerCase.outputs.lower_repository }}:1.20.1-6.0.0-forge
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Server with ${{ matrix.GameTestConfig }}
        run: gradle runGameTestServer -PGameTestConfig=${{ matrix.GameTestConfig }} -Dforge.enabledGameTestNamespaces=smartercontraptionstorage

      - uses: actions/upload-artifact@v4
        with:
          name: Test Artifact of ${{ matrix.GameTestConfig }}
          include-hidden-files: true
          path: |
            **/logs/
            **/crash-reports/
          retention-days: 7
        if: always()
